on:
  push:
    branches:
    - feat/gitub-actions
env:
  DOTNET_CORE_VERSION: 7.0.x
  CONTAINER_APP_NAME: metals-container-app
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20251003180304
  RESOURCE_GROUP: managedEnv20251003180304ResourceGroup
  CONTAINER_REGISTRY_NAME: registry20251003180829
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20251003180829.azurecr.io
jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.managedEnv20251003180304_SPN }}
    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.registry20251003180829_USERNAME_337B }}
        acrPassword: ${{ secrets.registry20251003180829_PASSWORD_337B }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
